[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "public"

[build.environment]
  NODE_ENV = "production"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"